# Generated by Django 4.1.7 on 2023-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_card_expiration_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='is_prof',
            field=models.BooleanField(default=True),
        ),
    ]
